version: "3.7"
services:
  front:
    restart: always
    build:
      context: museum-client
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: "http://localhost:8082"
    ports:
      - 3000:3000
    depends_on:
      - back
  postgres_db:
    image: postgres:10.5
    expose:
      - 5432
    environment:
      - POSTGRES_DB=pbz2
      - POSTGRES_USER=pbz2
      - POSTGRES_PASSWORD=pbz2
  db_migrations:
    restart: on-failure
    build:
      context: api-server-with-auth
      dockerfile: Dockerfile.migrations
    command: "-path=/migration/ -database postgres://pbz2:pbz2@postgres_db:5432/pbz2?sslmode=disable up"
    depends_on:
      - postgres_db
  back:
    restart: always
    build:
      context: api-server-with-auth
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: "8082"
      DB_ADDR: "postgresql://pbz2:pbz2@postgres_db:5432/pbz2?sslmode=disable"
      OAUTH_GOOGLE_ID: $OAUTH_GOOGLE_ID
      OAUTH_GOOGLE_SECRET: $OAUTH_GOOGLE_SECRET
      OAUTH_DISCORD_ID: $OAUTH_DISCORD_ID
      OAUTH_DISCORD_SECRET: $OAUTH_DISCORD_SECRET
      OAUTH_GITHUB_ID: $OAUTH_GITHUB_ID
      OAUTH_GITHUB_SECRET: $OAUTH_GITHUB_SECRET
      OAUTH_GOOGLE_REDIRECT_URL: "http://localhost:8082/callback/google"
      OAUTH_DISCORD_REDIRECT_URL: "http://localhost:8082/callback/discord"
      OAUTH_GITHUB_REDIRECT_URL: "http://localhost:8082/callback/github"
    ports:
      - 8082:8082
    depends_on:
      - postgres_db
